#!/usr/bin/env bash
# Variables 
	SYSDFLTUSRPTH="$HOME/.config/systemd/user"
	LIBHOME="$HOME/.local/lib"
	CFGHOME="$HOME/.config/pipewire/"
	REPODIR="$( dirname -- "$0"; )"
	RNNOISEREPO=werman/noise-suppression-for-voice
	# URL for current release, all modern releases won't work for some reason 
	# URL=$(curl -v https://api.github.com/repos/$RNNOISEREPO/releases/latest 2>&1 | egrep -wi 'linux' | cut -d '"' -f 4)
	URL="https://github.com/werman/noise-suppression-for-voice/releases/download/v0.91/linux_rnnoise_bin_x64.tar.gz"
#

function donemsg () {
	printf "\b\b\b, done.\n"
}

function getrnnoise () {
	printf "Getting rnnoise libs..."
	mkdir -p $LIBHOME
	wget $URL &>/dev/null
	tar -xf $REPODIR/linux_rnnoise_bin_x64.tar.gz
	cp "$REPODIR/bin/ladspa/librnnoise_ladspa.so" $LIBHOME
	donemsg
}

function mkpwconf () {
	printf "Creating config file..."
	mkdir -p $CFGHOME
	sed -i "s|123321|$HOME|g" $REPODIR/pwcforigin.conf
	cp $REPODIR/pwcforigin.conf $CFGHOME/rnnoise-filter.conf
	donemsg
} 

function getservice () {
	printf "Creating and starting rnnoise.service..."
	mkdir -p $SYSDFLTUSRPTH
	sed -i "s|123321|$HOME|g" $REPODIR/rnnoise.service
	cp $REPODIR/rnnoise.service $SYSDFLTUSRPTH
	systemctl --user enable --now rnnoise.service
	donemsg
}

function main () {
	getrnnoise
	mkpwconf
	getservice
}
main